name: ercross
description: "Ercross is a webcam provider client"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.1
  flutter_webrtc: ^0.11.7
  shared_preferences: ^2.3.2
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#FFFEFE"
  image: "assets/images/webcam.png"
  android: true
  fullscreen: true
  android_12:
    image: "assets/images/webcam.png"
    color: "#FFFEFE"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/light.ttf
          weight: 300
        - asset: assets/fonts/ubuntu/medium.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/regular.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/regular.ttf
          weight: 600
        - asset: assets/fonts/ubuntu/bold.ttf
          weight: 700
